In [2]:
import pandas as pd 
import numpy as np

- For each question, take the average of EEG wave values.

- Add the Response Time column, which will be used as the target variable.

- Add an Eye Movement column, where the average of the eye movement values is included.

- Combine these columns to form the dataset.

- Extract all relevant features from EEG and eye movement data.

- Set Response Time as the target value, while all other columns act as features.

- For 38 participants, merge the data across all questions (Question Key 1–38) to form the final dataset.

In [3]:
df = pd.read_csv('C:\\Users\\ASUS\\OneDrive\\Desktop\\IITB_internship\\STData\\STData\\1\\1_PSY.csv')

In [4]:
df.head()

,Key,Category,QuestionNumber,matchOrnomatch,Difficulty,verdict,ResponseTime,routineStart,routineStamp,routineEnd,Cat2FeedbackTime
0,1spl1,1,spl1,match,Easy,CORRECT,10.369816,1680003250,"28/03/2023, 17:04:09",1680003260,NaN
1,1spl2,1,spl2,nomatch,Easy,CORRECT,7.913991,1680003260,"28/03/2023, 17:04:20",1680003268,NaN
2,1Item1,1,Item1,match,Easy,CORRECT,7.654472,1680003268,"28/03/2023, 17:04:28",1680003276,NaN
3,1Item2,1,Item2,match,Easy,CORRECT,14.597205,1680003276,"28/03/2023, 17:04:35",1680003290,NaN
4,1Item3,1,Item3,match,Easy,CORRECT,16.476565,1680003291,"28/03/2023, 17:04:50",1680003307,NaN

In [ ]:
import pandas as pd
import glob


files = glob.glob(r"C:\Users\ASUS\OneDrive\Desktop\IITB_internship\STData\STData\*\*_PSY.csv")
all_data = []
for i, file in enumerate(files, start=1):
    df = pd.read_csv(file)
    df_new = df[['Key', 'ResponseTime','Category']].copy()
    df_new['Participant'] = i
    all_data.append(df_new)
final_df1 = pd.concat(all_data, ignore_index=True)

In [4]:
final_df1.rename(columns={'Key': 'QuestionKey'}, inplace=True)

In [5]:
final_df1

     QuestionKey  ResponseTime  Category  Participant
0          1spl1     10.369816         1            1
1          1spl2      7.913991         1            1
2         1Item1      7.654472         1            1
3         1Item2     14.597205         1            1
4         1Item3     16.476565         1            1
...          ...           ...       ...          ...
1443     3Item17     10.554283         3           38
1444     3Item19     15.000987         3           38
1445     3Item11     13.793000         3           38
1446      3Item4      3.460699         3           38
1447     3Item13      2.000000         3           38

[1448 rows x 4 columns]

In [6]:
df_eeg = pd.read_csv('C:\\Users\\ASUS\\OneDrive\\Desktop\\IITB_internship\\STData\\STData\\1\\1_EEG.csv')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\2127128177.py:1: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eeg = pd.read_csv('C:\\Users\\ASUS\\OneDrive\\Desktop\\IITB_internship\\STData\\STData\\1\\1_EEG.csv')

In [7]:
df_eeg.columns

Index(['TimeStamp', 'UnixTime', 'QuestionKey', 'Delta_TP9', 'Delta_AF7',
       'Delta_AF8', 'Delta_TP10', 'Theta_TP9', 'Theta_AF7', 'Theta_AF8',
       'Theta_TP10', 'Alpha_TP9', 'Alpha_AF7', 'Alpha_AF8', 'Alpha_TP10',
       'Beta_TP9', 'Beta_AF7', 'Beta_AF8', 'Beta_TP10', 'Gamma_TP9',
       'Gamma_AF7', 'Gamma_AF8', 'Gamma_TP10', 'RAW_TP9', 'RAW_AF7', 'RAW_AF8',
       'RAW_TP10', 'AUX_RIGHT', 'Accelerometer_X', 'Accelerometer_Y',
       'Accelerometer_Z', 'Gyro_X', 'Gyro_Y', 'Gyro_Z', 'HeadBandOn',
       'HSI_TP9', 'HSI_AF7', 'HSI_AF8', 'HSI_TP10', 'Battery', 'Elements'],
      dtype='object')

In [18]:
df_eeg['QuestionKey'].unique()

array([nan, '1spl1', '1spl2', '1Item1', '1Item2', '1Item3', '1Item4',
       '1Item5', '1Item6', '1Item7', '1Item8', '1Item9', '1Item10',
       '2spl1', '2spl2', '2Item1', '2Item2', '2Item3', '2Item4', '2Item5',
       '2Item6', '2Item7', '2Item8', '2Item9', '2Item10', '3spl1',
       '3spl2', '3Item15', '3Item2', '3Item5', '3Item12', '3Item6',
       '3Item8', '3Item7', '3Item9', '3Item17', '3Item19', '3Item11',
       '3Item4', '3Item13', '3Item10'], dtype=object)

In [8]:
import pandas as pd
import glob

wave_cols = ['Delta_TP9', 'Delta_AF7', 'Delta_AF8', 'Delta_TP10',
             'Theta_TP9', 'Theta_AF7', 'Theta_AF8', 'Theta_TP10',
             'Alpha_TP9', 'Alpha_AF7', 'Alpha_AF8', 'Alpha_TP10',
             'Beta_TP9', 'Beta_AF7', 'Beta_AF8', 'Beta_TP10']

files = glob.glob(r"C:\Users\ASUS\OneDrive\Desktop\IITB_internship\STData\STData\*\*_EEG.csv")
all_data = []

for i, file in enumerate(files, start=1):
    df = pd.read_csv(file)
    df_avg = df.groupby("QuestionKey")[wave_cols].mean().reset_index()
    df_avg["Participant"] = i
    all_data.append(df_avg)

final_df = pd.concat(all_data, ignore_index=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\3547780949.py:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

In [9]:
final_df

,QuestionKey,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,Alpha_TP9,Alpha_AF7,Alpha_AF8,Alpha_TP10,Beta_TP9,Beta_AF7,Beta_AF8,Beta_TP10,Participant
0,1Item1,0.827583,0.614266,0.802591,1.125673,0.732818,0.096184,0.317005,0.915437,0.896879,0.184076,0.423028,1.192328,0.569635,-0.316119,-0.098881,1.299411,1
1,1Item10,1.068161,0.605479,0.826938,1.224446,0.845977,0.169073,0.451087,0.999596,1.120050,0.219168,0.514472,1.144908,0.593766,-0.292831,-0.120923,1.322036,1
2,1Item2,0.960843,0.365654,0.680243,1.367405,0.808685,0.103491,0.326014,0.848162,1.126493,0.183033,0.440287,1.118666,0.526759,-0.384990,-0.218671,1.272737,1
3,1Item3,0.882369,0.468913,0.805100,1.033502,0.691901,0.109226,0.355050,0.639964,0.935221,0.208825,0.407962,1.000188,0.525849,-0.351635,-0.207062,1.265718,1
4,1Item4,0.804393,0.538407,0.604720,1.269374,0.689119,0.103516,0.253462,0.807940,1.035324,0.119487,0.373115,0.914857,0.536072,-0.395744,-0.222883,1.243855,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1357,3Item6,1.222892,1.229016,0.291774,0.940035,0.769694,0.877582,0.095951,0.620989,0.829850,0.960138,0.259314,0.764930,0.481024,0.320232,0.713880,0.498635,38
1358,3Item7,0.927512,1.130435,0.630141,0.841076,0.690032,0.703453,0.106869,0.541878,0.843459,0.769299,0.374317,0.751704,0.384957,0.258952,0.766349,0.423602,38
1359,3Item8,0.762607,1.310647,0.402410,0.531718,0.520179,0.872889,0.010762,0.351696,0.753362,0.872138,0.246823,0.494089,0.467846,0.366058,0.755041,0.366934,38
1360,3Item9,1.058547,1.334666,0.450615,0.880808,0.793230,0.877694,0.143415,0.694429,0.838965,0.861817,0.261661,0.833173,0.490235,0.345253,0.806353,0.435886,38
1361,3spl1,0.868774,0.936052,0.569832,0.864833,0.388490,0.673359,0.290660,0.368471,0.835778,0.694235,0.399298,0.749895,0.530965,0.362104,0.690216,0.533447,38

In [10]:
final_df1

     QuestionKey  ResponseTime  Category  Participant
0          1spl1     10.369816         1            1
1          1spl2      7.913991         1            1
2         1Item1      7.654472         1            1
3         1Item2     14.597205         1            1
4         1Item3     16.476565         1            1
...          ...           ...       ...          ...
1443     3Item17     10.554283         3           38
1444     3Item19     15.000987         3           38
1445     3Item11     13.793000         3           38
1446      3Item4      3.460699         3           38
1447     3Item13      2.000000         3           38

[1448 rows x 4 columns]

In [11]:
merged = pd.merge(final_df, final_df1, on=["Participant", "QuestionKey"], how="inner")

In [12]:
merged

,QuestionKey,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,Alpha_TP9,Alpha_AF7,Alpha_AF8,Alpha_TP10,Beta_TP9,Beta_AF7,Beta_AF8,Beta_TP10,Participant,ResponseTime,Category
0,1Item1,0.827583,0.614266,0.802591,1.125673,0.732818,0.096184,0.317005,0.915437,0.896879,0.184076,0.423028,1.192328,0.569635,-0.316119,-0.098881,1.299411,1,7.654472,1
1,1Item10,1.068161,0.605479,0.826938,1.224446,0.845977,0.169073,0.451087,0.999596,1.120050,0.219168,0.514472,1.144908,0.593766,-0.292831,-0.120923,1.322036,1,21.042414,1
2,1Item2,0.960843,0.365654,0.680243,1.367405,0.808685,0.103491,0.326014,0.848162,1.126493,0.183033,0.440287,1.118666,0.526759,-0.384990,-0.218671,1.272737,1,14.597205,1
3,1Item3,0.882369,0.468913,0.805100,1.033502,0.691901,0.109226,0.355050,0.639964,0.935221,0.208825,0.407962,1.000188,0.525849,-0.351635,-0.207062,1.265718,1,16.476565,1
4,1Item4,0.804393,0.538407,0.604720,1.269374,0.689119,0.103516,0.253462,0.807940,1.035324,0.119487,0.373115,0.914857,0.536072,-0.395744,-0.222883,1.243855,1,17.546052,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,3Item6,1.222892,1.229016,0.291774,0.940035,0.769694,0.877582,0.095951,0.620989,0.829850,0.960138,0.259314,0.764930,0.481024,0.320232,0.713880,0.498635,38,6.556124,3
1360,3Item7,0.927512,1.130435,0.630141,0.841076,0.690032,0.703453,0.106869,0.541878,0.843459,0.769299,0.374317,0.751704,0.384957,0.258952,0.766349,0.423602,38,6.129601,3
1361,3Item8,0.762607,1.310647,0.402410,0.531718,0.520179,0.872889,0.010762,0.351696,0.753362,0.872138,0.246823,0.494089,0.467846,0.366058,0.755041,0.366934,38,10.204437,3
1362,3Item9,1.058547,1.334666,0.450615,0.880808,0.793230,0.877694,0.143415,0.694429,0.838965,0.861817,0.261661,0.833173,0.490235,0.345253,0.806353,0.435886,38,15.968929,3
1363,3spl1,0.868774,0.936052,0.569832,0.864833,0.388490,0.673359,0.290660,0.368471,0.835778,0.694235,0.399298,0.749895,0.530965,0.362104,0.690216,0.533447,38,4.542019,3

In [13]:
df_eye = pd.read_csv('C:\\Users\\ASUS\\OneDrive\\Desktop\\IITB_internship\\STData\\STData\\1\\1_EYE.csv')

In [14]:
df_eye.columns

Index(['UnixTime', 'Row', 'QuestionKey', 'Timestamp', 'ET_GazeLeftx',
       'ET_GazeLefty', 'ET_GazeRightx', 'ET_GazeRighty', 'ET_PupilLeft',
       'ET_PupilRight', 'ET_TimeSignal', 'ET_DistanceLeft', 'ET_DistanceRight',
       'ET_CameraLeftX', 'ET_CameraLeftY', 'ET_CameraRightX',
       'ET_CameraRightY', 'ET_ValidityLeft', 'ET_ValidityRight'],
      dtype='object')

In [ ]:
# selecting important features from the eye columns 
import pandas as pd
import glob

eye_cols = ['ET_GazeLeftx','ET_GazeLefty','ET_GazeRightx','ET_GazeRighty',
            'ET_PupilLeft','ET_PupilRight','ET_DistanceLeft','ET_DistanceRight']
files = glob.glob(r"C:\Users\ASUS\OneDrive\Desktop\IITB_internship\STData\STData\*\*_EYE.csv")

all_eye = []

for i, file in enumerate(files, start=1):
    df_eye = pd.read_csv(file)
    df_eye_avg = df_eye.groupby("QuestionKey")[eye_cols].mean().reset_index()
    df_eye_avg["Participant"] = i 
    
    all_eye.append(df_eye_avg)


final_eye_df = pd.concat(all_eye, ignore_index=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14040\1892545729.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eye = pd.read_csv(file)

In [ ]:
df_IVT = pd.read_csv("C:\\Users\\ASUS\\OneDrive\\Desktop\\IITB_internship\\STData\\STData\1\1_IVT.csv")

In [16]:
merged.head()

,QuestionKey,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,Alpha_TP9,Alpha_AF7,Alpha_AF8,Alpha_TP10,Beta_TP9,Beta_AF7,Beta_AF8,Beta_TP10,Participant,ResponseTime,Category
0,1Item1,0.827583,0.614266,0.802591,1.125673,0.732818,0.096184,0.317005,0.915437,0.896879,0.184076,0.423028,1.192328,0.569635,-0.316119,-0.098881,1.299411,1,7.654472,1
1,1Item10,1.068161,0.605479,0.826938,1.224446,0.845977,0.169073,0.451087,0.999596,1.120050,0.219168,0.514472,1.144908,0.593766,-0.292831,-0.120923,1.322036,1,21.042414,1
2,1Item2,0.960843,0.365654,0.680243,1.367405,0.808685,0.103491,0.326014,0.848162,1.126493,0.183033,0.440287,1.118666,0.526759,-0.384990,-0.218671,1.272737,1,14.597205,1
3,1Item3,0.882369,0.468913,0.805100,1.033502,0.691901,0.109226,0.355050,0.639964,0.935221,0.208825,0.407962,1.000188,0.525849,-0.351635,-0.207062,1.265718,1,16.476565,1
4,1Item4,0.804393,0.538407,0.604720,1.269374,0.689119,0.103516,0.253462,0.807940,1.035324,0.119487,0.373115,0.914857,0.536072,-0.395744,-0.222883,1.243855,1,17.546052,1

In [17]:
final_eye_df

,QuestionKey,ET_GazeLeftx,ET_GazeLefty,ET_GazeRightx,ET_GazeRighty,ET_PupilLeft,ET_PupilRight,ET_DistanceLeft,ET_DistanceRight,Participant
0,1Item1,812.504357,498.212418,849.327887,529.728758,0.177434,0.279286,551.719324,556.047447,1
1,1Item10,753.546535,504.263366,771.059802,505.335446,0.133114,0.083240,519.907194,513.148632,1
2,1Item2,837.555365,480.426370,865.590753,504.143836,0.146769,0.253750,545.999649,549.390933,1
3,1Item3,905.771877,469.903895,912.987860,478.987355,0.055191,0.038953,531.116385,520.917207,1
4,1Item4,777.932099,456.263058,818.310541,482.328585,0.080009,0.165165,536.694378,542.917631,1
...,...,...,...,...,...,...,...,...,...,...
1441,3Item6,871.946633,509.462516,882.358323,517.939009,0.311770,0.320131,556.576293,546.113491,38
1442,3Item7,756.281633,472.172789,815.941497,499.089796,0.268900,0.396749,563.099124,572.474481,38
1443,3Item8,809.358367,541.511020,853.950204,584.293878,0.307474,0.483357,570.901450,586.174962,38
1444,3Item9,771.430882,435.814293,800.350026,460.383412,0.338934,0.404867,575.042696,571.521842,38
1445,3spl1,918.954128,464.554128,945.957798,510.893578,0.341229,0.363373,587.867410,588.284109,38

In [18]:
final = pd.merge(merged,final_eye_df,on=["Participant", "QuestionKey"], how="inner")

In [19]:
final

,QuestionKey,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,Alpha_TP9,...,ResponseTime,Category,ET_GazeLeftx,ET_GazeLefty,ET_GazeRightx,ET_GazeRighty,ET_PupilLeft,ET_PupilRight,ET_DistanceLeft,ET_DistanceRight
0,1Item1,0.827583,0.614266,0.802591,1.125673,0.732818,0.096184,0.317005,0.915437,0.896879,...,7.654472,1,812.504357,498.212418,849.327887,529.728758,0.177434,0.279286,551.719324,556.047447
1,1Item10,1.068161,0.605479,0.826938,1.224446,0.845977,0.169073,0.451087,0.999596,1.120050,...,21.042414,1,753.546535,504.263366,771.059802,505.335446,0.133114,0.083240,519.907194,513.148632
2,1Item2,0.960843,0.365654,0.680243,1.367405,0.808685,0.103491,0.326014,0.848162,1.126493,...,14.597205,1,837.555365,480.426370,865.590753,504.143836,0.146769,0.253750,545.999649,549.390933
3,1Item3,0.882369,0.468913,0.805100,1.033502,0.691901,0.109226,0.355050,0.639964,0.935221,...,16.476565,1,905.771877,469.903895,912.987860,478.987355,0.055191,0.038953,531.116385,520.917207
4,1Item4,0.804393,0.538407,0.604720,1.269374,0.689119,0.103516,0.253462,0.807940,1.035324,...,17.546052,1,777.932099,456.263058,818.310541,482.328585,0.080009,0.165165,536.694378,542.917631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,3Item6,1.222892,1.229016,0.291774,0.940035,0.769694,0.877582,0.095951,0.620989,0.829850,...,6.556124,3,871.946633,509.462516,882.358323,517.939009,0.311770,0.320131,556.576293,546.113491
1360,3Item7,0.927512,1.130435,0.630141,0.841076,0.690032,0.703453,0.106869,0.541878,0.843459,...,6.129601,3,756.281633,472.172789,815.941497,499.089796,0.268900,0.396749,563.099124,572.474481
1361,3Item8,0.762607,1.310647,0.402410,0.531718,0.520179,0.872889,0.010762,0.351696,0.753362,...,10.204437,3,809.358367,541.511020,853.950204,584.293878,0.307474,0.483357,570.901450,586.174962
1362,3Item9,1.058547,1.334666,0.450615,0.880808,0.793230,0.877694,0.143415,0.694429,0.838965,...,15.968929,3,771.430882,435.814293,800.350026,460.383412,0.338934,0.404867,575.042696,571.521842
1363,3spl1,0.868774,0.936052,0.569832,0.864833,0.388490,0.673359,0.290660,0.368471,0.835778,...,4.542019,3,918.954128,464.554128,945.957798,510.893578,0.341229,0.363373,587.867410,588.284109

In [20]:
# csv file conversion
final.to_csv("final_final_data.csv", index=False)

## Linear regression training

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [6]:
df = pd.read_csv("C:\\Users\\ASUS\\OneDrive\\Desktop\\IITB_internship\\final_data.csv")

In [7]:
# data cleaning 
# Drop categorical columns
df_num = df.drop(columns=["QuestionKey", "Participant"], errors="ignore")
df_num = df_num.replace([np.inf, -np.inf], np.nan)
df_num = df_num.dropna()

In [8]:

X = df_num.drop(columns=["ResponseTime"]) # Features (X)
y = df_num["ResponseTime"]  #Target (y)

In [9]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = model.predict(X_test)

## Evaluation

In [12]:

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Model Performance:")
print(f"R² Score      : {r2:.4f}")
print(f"MAE           : {mae:.4f}")
print(f"RMSE          : {rmse:.4f}")

Model Performance:
R² Score      : 0.1174
MAE           : 9.1926
RMSE          : 13.1287

## Ridge regression

In [14]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
ridge = Ridge(alpha=1.0)

In [15]:
ridge.fit(X_train, y_train)

Ridge()

In [16]:
y_pred_ridge = ridge.predict(X_test)

## evaluation of ridge regression

In [17]:
r2 = r2_score(y_test, y_pred_ridge)
mae = mean_absolute_error(y_test, y_pred_ridge)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_ridge))

print("Model Performance:")
print(f"R² Score      : {r2:.4f}")
print(f"MAE           : {mae:.4f}")
print(f"RMSE          : {rmse:.4f}")

Model Performance:
R² Score      : 0.1187
MAE           : 9.1837
RMSE          : 13.1191

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

## Random forest regressor

In [18]:

from sklearn.ensemble import RandomForestRegressor

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [20]:
rf = RandomForestRegressor(
    n_estimators=200,      # number of trees
    max_depth=None,        # let trees grow deep
    random_state=42,
    n_jobs=-1              # use all CPU cores
)

In [21]:
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [22]:
y_pred = rf.predict(X_test)

## Evaluation

In [23]:
# Evaluate
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Random Forest Regressor Performance:")
print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

Random Forest Regressor Performance:
R² Score : 0.2559
MAE      : 8.4628
RMSE     : 12.0544

## gradient boosting regressor

In [24]:
from sklearn.ensemble import GradientBoostingRegressor
gbr = GradientBoostingRegressor(
    n_estimators=300,   # number of boosting stages (trees)
    learning_rate=0.05, # step size shrinkage
    max_depth=5,        # depth of individual trees
    random_state=42
)

In [25]:
gbr.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, max_depth=5, n_estimators=300,
                          random_state=42)

In [26]:
y_pred = gbr.predict(X_test)

# Evaluate

In [ ]:

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Gradient Boosting Regressor Performance:")
print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

Gradient Boosting Regressor Performance:
R² Score : 0.3255
MAE      : 7.8779
RMSE     : 11.4765

In [109]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.0.4-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in e:\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in e:\anaconda3\lib\site-packages (from xgboost) (1.16.0)
Downloading xgboost-3.0.4-py3-none-win_amd64.whl (56.8 MB)
   ---------------------------------------- 0.0/56.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/56.8 MB ? eta -:--:--
   ---------------------------------------- 0.3/56.8 MB ? eta -:--:--
   ---------------------------------------- 0.3/56.8 MB ? eta -:--:--
   ---------------------------------------- 0.5/56.8 MB 699.0 kB/s eta 0:01:21
    --------------------------------------- 0.8/56.8 MB 819.2 kB/s eta 0:01:09
    --------------------------------------- 0.8/56.8 MB 819.2 kB/s eta 0:01:09
    --------------------------------------- 1.0/56.8 MB 883.6 kB/s eta 0:01:04
    --------------------------------------- 1.3/56.8 MB 945.5 kB/s eta 0:00:59
   - -------------------------------------- 1.6/56.8 MB 943.0 kB/s eta 0:00:59
   - -------------------------------------- 1.8/56.8 MB 986.7 kB/s eta 0:00:56
   - -------------------------------------- 2.4/56.8 MB 1.1 MB/s eta 0:00:50
   - -------------------------------------- 2.6/56.8 MB 1.2 MB/s eta 0:00:47
   -- ------------------------------------- 3.1/56.8 MB 1.3 MB/s eta 0:00:43
   -- ------------------------------------- 3.7/56.8 MB 1.3 MB/s eta 0:00:40
   -- ------------------------------------- 4.2/56.8 MB 1.4 MB/s eta 0:00:37
   --- ------------------------------------ 4.7/56.8 MB 1.5 MB/s eta 0:00:35
   --- ------------------------------------ 5.2/56.8 MB 1.6 MB/s eta 0:00:33
   ---- ----------------------------------- 5.8/56.8 MB 1.7 MB/s eta 0:00:31
   ---- ----------------------------------- 6.6/56.8 MB 1.8 MB/s eta 0:00:29
   ---- ----------------------------------- 7.1/56.8 MB 1.8 MB/s eta 0:00:28
   ----- ---------------------------------- 7.9/56.8 MB 1.9 MB/s eta 0:00:26
   ------ --------------------------------- 8.7/56.8 MB 2.0 MB/s eta 0:00:24
   ------ --------------------------------- 9.4/56.8 MB 2.1 MB/s eta 0:00:23
   ------- -------------------------------- 10.5/56.8 MB 2.2 MB/s eta 0:00:22
   ------- -------------------------------- 11.0/56.8 MB 2.2 MB/s eta 0:00:21
   -------- ------------------------------- 11.5/56.8 MB 2.3 MB/s eta 0:00:20
   -------- ------------------------------- 12.1/56.8 MB 2.2 MB/s eta 0:00:20
   --------- ------------------------------ 12.8/56.8 MB 2.3 MB/s eta 0:00:20
   --------- ------------------------------ 13.6/56.8 MB 2.4 MB/s eta 0:00:19
   ---------- ----------------------------- 14.4/56.8 MB 2.4 MB/s eta 0:00:18
   ---------- ----------------------------- 14.9/56.8 MB 2.4 MB/s eta 0:00:18
   ---------- ----------------------------- 15.5/56.8 MB 2.4 MB/s eta 0:00:18
   ----------- ---------------------------- 16.3/56.8 MB 2.4 MB/s eta 0:00:17
   ------------ --------------------------- 17.3/56.8 MB 2.5 MB/s eta 0:00:16
   ------------ --------------------------- 18.1/56.8 MB 2.6 MB/s eta 0:00:16
   ------------- -------------------------- 18.9/56.8 MB 2.6 MB/s eta 0:00:15
   -------------- ------------------------- 19.9/56.8 MB 2.7 MB/s eta 0:00:14
   -------------- ------------------------- 20.4/56.8 MB 2.7 MB/s eta 0:00:14
   --------------- ------------------------ 21.5/56.8 MB 2.7 MB/s eta 0:00:13
   --------------- ------------------------ 22.3/56.8 MB 2.8 MB/s eta 0:00:13
   ---------------- ----------------------- 23.1/56.8 MB 2.8 MB/s eta 0:00:13
   ---------------- ----------------------- 23.9/56.8 MB 2.8 MB/s eta 0:00:12
   ----------------- ---------------------- 24.6/56.8 MB 2.8 MB/s eta 0:00:12
   ----------------- ---------------------- 25.4/56.8 MB 2.8 MB/s eta 0:00:12
   ------------------ --------------------- 26.0/56.8 MB 2.8 MB/s eta 0:00:11
   ------------------ --------------------- 26.7/56.8 MB 2.9 MB/s eta 0:00:11
   ------------------- -------------------- 27.5/56.8 MB 2.9 MB/s eta 0:00:11
   ------------------- -------------------- 28.0/56.8 MB 2.9 MB/s eta 0:00:11
   -------------------- ------------------- 28.8/56.8 MB 2.9 MB/s eta 0:00:10
   --------------------- ------------------ 29.9/56.8 MB 2.9 MB/s eta 0:00:10
   --------------------- ------------------ 30.4/56.8 MB 2.9 MB/s eta 0:00:10
   --------------------- ------------------ 31.2/56.8 MB 2.9 MB/s eta 0:00:09
   ---------------------- ----------------- 31.7/56.8 MB 2.9 MB/s eta 0:00:09
   ---------------------- ----------------- 32.2/56.8 MB 2.9 MB/s eta 0:00:09
   ----------------------- ---------------- 32.8/56.8 MB 2.9 MB/s eta 0:00:09
   ----------------------- ---------------- 33.0/56.8 MB 2.9 MB/s eta 0:00:09
   ----------------------- ---------------- 33.6/56.8 MB 2.9 MB/s eta 0:00:09
   ----------------------- ---------------- 33.8/56.8 MB 2.9 MB/s eta 0:00:09
   ------------------------ --------------- 34.3/56.8 MB 2.8 MB/s eta 0:00:08
   ------------------------ --------------- 35.1/56.8 MB 2.9 MB/s eta 0:00:08
   ------------------------- -------------- 35.9/56.8 MB 2.9 MB/s eta 0:00:08
   ------------------------- -------------- 36.4/56.8 MB 2.9 MB/s eta 0:00:08
   -------------------------- ------------- 37.0/56.8 MB 2.9 MB/s eta 0:00:07
   -------------------------- ------------- 37.5/56.8 MB 2.9 MB/s eta 0:00:07
   -------------------------- ------------- 38.0/56.8 MB 2.8 MB/s eta 0:00:07
   --------------------------- ------------ 39.1/56.8 MB 2.9 MB/s eta 0:00:07
   ---------------------------- ----------- 39.8/56.8 MB 2.9 MB/s eta 0:00:06
   ---------------------------- ----------- 40.4/56.8 MB 2.9 MB/s eta 0:00:06
   ---------------------------- ----------- 41.2/56.8 MB 2.9 MB/s eta 0:00:06
   ----------------------------- ---------- 41.7/56.8 MB 2.9 MB/s eta 0:00:06
   ----------------------------- ---------- 42.2/56.8 MB 2.9 MB/s eta 0:00:06
   ------------------------------ --------- 42.7/56.8 MB 2.9 MB/s eta 0:00:05
   ------------------------------ --------- 43.3/56.8 MB 2.9 MB/s eta 0:00:05
   ------------------------------ --------- 43.8/56.8 MB 2.9 MB/s eta 0:00:05
   ------------------------------- -------- 44.3/56.8 MB 2.9 MB/s eta 0:00:05
   ------------------------------- -------- 44.8/56.8 MB 2.9 MB/s eta 0:00:05
   ------------------------------- -------- 45.1/56.8 MB 2.8 MB/s eta 0:00:05
   -------------------------------- ------- 45.6/56.8 MB 2.8 MB/s eta 0:00:04
   -------------------------------- ------- 46.1/56.8 MB 2.8 MB/s eta 0:00:04
   -------------------------------- ------- 46.7/56.8 MB 2.8 MB/s eta 0:00:04
   --------------------------------- ------ 46.9/56.8 MB 2.8 MB/s eta 0:00:04
   --------------------------------- ------ 47.4/56.8 MB 2.8 MB/s eta 0:00:04
   --------------------------------- ------ 48.0/56.8 MB 2.8 MB/s eta 0:00:04
   ---------------------------------- ----- 48.8/56.8 MB 2.8 MB/s eta 0:00:03
   ----------------------------------- ---- 49.8/56.8 MB 2.8 MB/s eta 0:00:03
   ----------------------------------- ---- 50.6/56.8 MB 2.8 MB/s eta 0:00:03
   ----------------------------------- ---- 50.9/56.8 MB 2.8 MB/s eta 0:00:03
   ------------------------------------ --- 51.9/56.8 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 53.2/56.8 MB 2.9 MB/s eta 0:00:02
   -------------------------------------- - 54.3/56.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  55.6/56.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  56.6/56.8 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 56.8/56.8 MB 2.9 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.0.4

## xg boost regressor

In [28]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=500,        # number of boosting rounds
    learning_rate=0.05,      # smaller = more accurate but slower
    max_depth=6,             # tree depth
    subsample=0.8,           # use 80% data per tree (prevents overfitting)
    colsample_bytree=0.8,    # use 80% features per tree
    random_state=42,
    n_jobs=-1
)

In [29]:
xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [30]:
y_pred = xgb.predict(X_test)

# Evaluate

In [ ]:

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("XGBoost Regressor Performance:")
print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

XGBoost Regressor Performance:
R² Score : 0.3034
MAE      : 8.0588
RMSE     : 11.6636

## LSTM trainig - performed  worst

In [32]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
y_scaled = scaler.fit_transform(y.values.reshape(-1,1))

In [33]:
!pip install tensorflow

Requirement already satisfied: tensorflow in e:\anaconda3\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in e:\anaconda3\lib\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in e:\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in e:\anaconda3\lib\site-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in e:\anaconda3\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in e:\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in e:\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in e:\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in e:\anaconda3\lib\site-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf>=5.28.0 in e:\anaconda3\lib\site-packages (from tensorflow) (6.32.0)
Requirement already satisfied: requests<3,>=2.21.0 in e:\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in e:\anaconda3\lib\site-packages (from tensorflow) (75.1.0)
Requirement already satisfied: six>=1.12.0 in e:\anaconda3\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in e:\anaconda3\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in e:\anaconda3\lib\site-packages (from tensorflow) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in e:\anaconda3\lib\site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in e:\anaconda3\lib\site-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.20.0 in e:\anaconda3\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in e:\anaconda3\lib\site-packages (from tensorflow) (3.11.3)
Requirement already satisfied: numpy>=1.26.0 in e:\anaconda3\lib\site-packages (from tensorflow) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in e:\anaconda3\lib\site-packages (from tensorflow) (3.11.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in e:\anaconda3\lib\site-packages (from tensorflow) (0.5.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in e:\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in e:\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (13.7.1)
Requirement already satisfied: namex in e:\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in e:\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in e:\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2024.12.14)
Requirement already satisfied: markdown>=2.6.8 in e:\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.4.1)
Requirement already satisfied: pillow in e:\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (10.4.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in e:\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in e:\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in e:\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (2.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in e:\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.0)

In [ ]:


timesteps = 5                 # lookback window
n_features = X.shape[1]       # number of input features

# Create sequences
def create_sequences(X, y, timesteps):
    X_seq, y_seq = [], []
    for i in range(len(X) - timesteps):
        X_seq.append(X[i:i+timesteps])
        y_seq.append(y[i+timesteps])
    return np.array(X_seq), np.array(y_seq)

X_seq, y_seq = create_sequences(X.values, y.values, timesteps)

print(X_seq.shape, y_seq.shape)

(1358, 5, 24) (1358,)

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_seq, y_seq, test_size=0.2, random_state=42)

In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(timesteps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

e:\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [37]:
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)
y_pred = model.predict(X_test)

Epoch 1/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 37610.9102 - val_loss: 9903.0713
Epoch 2/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4135.6943 - val_loss: 2889.3201
Epoch 3/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1697.3873 - val_loss: 1767.4097
Epoch 4/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1109.7676 - val_loss: 1227.3523
Epoch 5/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1059.1926 - val_loss: 1092.7896
Epoch 6/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 767.5226 - val_loss: 935.7728
Epoch 7/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 668.9074 - val_loss: 667.7933
Epoch 8/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 578.8370 - val_loss: 548.4184
Epoch 9/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 533.9474 - val_loss: 535.5919
Epoch 10/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 491.0966 - val_loss: 540.9089
Epoch 11/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 494.7041 - val_loss: 494.7591
Epoch 12/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 433.4086 - val_loss: 456.1999
Epoch 13/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 409.9401 - val_loss: 409.6747
Epoch 14/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 435.5769 - val_loss: 454.7878
Epoch 15/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 383.2115 - val_loss: 384.3521
Epoch 16/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 359.2690 - val_loss: 434.6997
Epoch 17/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 349.7238 - val_loss: 407.4429
Epoch 18/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 332.0920 - val_loss: 381.2692
Epoch 19/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 358.8251 - val_loss: 349.3370
Epoch 20/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 314.8473 - val_loss: 341.9521
Epoch 21/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 352.1781 - val_loss: 467.3051
Epoch 22/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 342.6203 - val_loss: 512.1699
Epoch 23/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 310.2942 - val_loss: 389.0808
Epoch 24/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 319.4328 - val_loss: 470.0767
Epoch 25/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 318.4442 - val_loss: 422.5269
Epoch 26/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 283.6658 - val_loss: 436.5052
Epoch 27/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 268.9464 - val_loss: 418.7320
Epoch 28/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 261.8720 - val_loss: 442.0558
Epoch 29/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 256.7729 - val_loss: 418.4387
Epoch 30/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 255.0748 - val_loss: 317.7716
Epoch 31/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 242.6690 - val_loss: 396.6086
Epoch 32/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 248.9551 - val_loss: 357.3841
Epoch 33/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 239.9206 - val_loss: 325.7303
Epoch 34/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 239.6134 - val_loss: 391.4148
Epoch 35/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 288.9223 - val_loss: 309.8734
Epoch 36/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 253.8795 - val_loss: 375.5429
Epoch 37/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 243.6965 - val_loss: 309.8417
Epoch 38/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 266.5315 - val_loss: 305.1547
Epoch 39/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 228.5331 - val_loss: 303.3176
Epoch 40/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 244.7027 - val_loss: 287.8073
Epoch 41/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 239.5553 - val_loss: 302.2249
Epoch 42/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 240.2736 - val_loss: 346.9457
Epoch 43/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 239.8031 - val_loss: 253.6676
Epoch 44/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 223.0836 - val_loss: 266.5863
Epoch 45/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 240.7852 - val_loss: 340.1057
Epoch 46/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 227.4985 - val_loss: 261.3356
Epoch 47/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 227.5394 - val_loss: 239.5012
Epoch 48/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 247.3276 - val_loss: 250.5782
Epoch 49/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 232.4936 - val_loss: 241.9787
Epoch 50/50
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 225.7501 - val_loss: 248.6120
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

In [38]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Predictions
y_pred = model.predict(X_test)

# Metrics
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("LSTM Regressor Performance:")
print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
LSTM Regressor Performance:
R² Score : -0.5008
MAE      : 12.0392
RMSE     : 17.5208

- LSTM performed worst 
- tried feature scaling to scale the values

In [39]:

from sklearn.preprocessing import StandardScaler

In [40]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [41]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # fit only on training set
X_test_scaled = scaler.transform(X_test)        # transform test set

In [47]:

lin_reg = LinearRegression()
lin_reg.fit(X_train_scaled, y_train)

LinearRegression()

In [48]:
ridge = Ridge(alpha=1.0)  
ridge.fit(X_train_scaled, y_train)

Ridge()

In [49]:

lasso = Lasso(alpha=0.001)
lasso.fit(X_train_scaled, y_train)

Lasso(alpha=0.001)

In [50]:
y_pred_lin = lin_reg.predict(X_test_scaled)
y_pred_ridge = ridge.predict(X_test_scaled)
y_pred_lasso = lasso.predict(X_test_scaled)

## Evaluation after scaling

In [51]:

# Function to evaluate model
def evaluate(y_true, y_pred, name):
    r2 = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    print(f"\n{name} Performance:")
    print(f"R² Score : {r2:.4f}")
    print(f"MAE      : {mae:.4f}")
    print(f"RMSE     : {rmse:.4f}")

# Evaluate all models
evaluate(y_test, y_pred_lin, "Linear Regression")
evaluate(y_test, y_pred_ridge, "Ridge Regression")
evaluate(y_test, y_pred_lasso, "Lasso Regression")

Linear Regression Performance:
R² Score : 0.1174
MAE      : 9.1926
RMSE     : 13.1287

Ridge Regression Performance:
R² Score : 0.1188
MAE      : 9.1750
RMSE     : 13.1182

Lasso Regression Performance:
R² Score : 0.1175
MAE      : 9.1908
RMSE     : 13.1281

In [52]:
models = {
    "Random Forest": RandomForestRegressor(
        n_estimators=300, max_depth=10, random_state=42, n_jobs=-1
    ),
    "Gradient Boosting": GradientBoostingRegressor(
        n_estimators=500, learning_rate=0.05, max_depth=5, random_state=42
    ),
    "XGBoost": XGBRegressor(
        n_estimators=500, learning_rate=0.05, max_depth=6,
        subsample=0.8, colsample_bytree=0.8, random_state=42, n_jobs=-1
    )
}

In [53]:
def evaluate(y_true, y_pred, name):
    r2 = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    print(f"\n{name} Performance:")
    print(f"R² Score : {r2:.4f}")
    print(f"MAE      : {mae:.4f}")
    print(f"RMSE     : {rmse:.4f}")
    return r2

best_model = None
best_score = -np.inf

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    score = evaluate(y_test, y_pred, name)
    if score > best_score:
        best_score = score
        best_model = (name, model)

print(f"\n🔥 Best Model: {best_model[0]} with R² = {best_score:.4f}")

Random Forest Performance:
R² Score : 0.2426
MAE      : 8.5187
RMSE     : 12.1614

Gradient Boosting Performance:
R² Score : 0.3181
MAE      : 7.8854
RMSE     : 11.5395

XGBoost Performance:
R² Score : 0.3034
MAE      : 8.0588
RMSE     : 11.6636

🔥 Best Model: Gradient Boosting with R² = 0.3181

In [54]:

def evaluate(y_true, y_pred, name):
    r2 = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    print(f"\n{name} Performance:")
    print(f"R² Score : {r2:.4f}")
    print(f"MAE      : {mae:.4f}")
    print(f"RMSE     : {rmse:.4f}")
    return r2

best_model = None
best_score = -np.inf

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    score = evaluate(y_test, y_pred, name)
    if score > best_score:
        best_score = score
        best_model = (name, model)

print(f"\n Best Model: {best_model[0]} with R² = {best_score:.4f}")

Random Forest Performance:
R² Score : 0.2426
MAE      : 8.5187
RMSE     : 12.1614

Gradient Boosting Performance:
R² Score : 0.3181
MAE      : 7.8854
RMSE     : 11.5395

XGBoost Performance:
R² Score : 0.3034
MAE      : 8.0588
RMSE     : 11.6636

 Best Model: Gradient Boosting with R² = 0.3181

- From the above training, the model did not give good results.

- The model was only able to explain around 30% variance, which is too low for acceptable performance.

- In the next file, we created a new data subset, which we considered as the final subset.

- In the earlier subset, we only used the average readings of EEG waves and eye-tracking features, which limited the model’s learning ability.

- To improve performance, in the final dataset we included minimum, maximum, average, and standard deviation values so that the model could capture more detailed feature variations.